# Blogcomment schema

# --- !Ups

DROP TABLE IF EXISTS BLOGCOMMENT;

CREATE TABLE BLOGCOMMENT(ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    POST_ID INT NOT NULL,
    FOREIGN KEY (POST_ID) REFERENCES BLOGPOST(ID),
    AUTHOR VARCHAR(256) NOT NULL,
    COMMENT TEXT NOT NULL);

INSERT INTO BLOGCOMMENT VALUES(1, 1, 'Peelo', 'Paska kommentti ekaan');
INSERT INTO BLOGCOMMENT VALUES(2, 1, 'Esko', 'Asiatonta settiä ekaan');

# --- !Downs
DROP TABLE BLOGCOMMENT;