# User schema

# --- !Ups

DROP TABLE IF EXISTS USER;

CREATE TABLE USER(ID Int PRIMARY KEY AUTO_INCREMENT NOT NULL,
AUTHOR BOOLEAN NOT NULL DEFAULT FALSE,
ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
VISIBLE BOOLEAN NOT NULL DEFAULT TRUE,
NICKNAME VARCHAR(64) NOT NULL,
REALNAME VARCHAR(128) NOT NULL,
EMAIL VARCHAR(256) NOT NULL,
PASSWORD VARCHAR(128) NOT NULL,
REGISTERDATE DATE NOT NULL,
SALT VARCHAR(29)  NOT NULL
);

# --- !Downs
DROP TABLE USER;